### ISSUE TITLE
Taiko issue

### ISSUE THREAD

**Issue by Fearboy1** [CoderOffka/ReplayRidor#4]
Taiko works randomly and hits wrong buttons.

**Comment by Kontorted** [comment]
Is the replay corrupt?
Is this an issue with all types of modes or Taiko in general?
Are you using a player replay or Auto Replay?
Are your binds matching with ReplayRidor's binds?

**Comment by CoderOffka** [comment]
![image](https://user-images.githubusercontent.com/11484976/41772473-75f8ba32-7621-11e8-8ae9-f94aedd3fe13.png)
No problems...
