### ISSUE TITLE
LzmaLib.h Error

### ISSUE THREAD

**Issue by Kag3rou** [CoderOffka/ReplayRidor#8]
I know it's included in libraries, but it still says that it cannot open/read the file and produces errors all over the place.

**Comment by Kag3rou** [comment]
I included LzmaLib.h, then it said 7zTypes.h, found it I believe through googling, included it, then it shit out 60 errors, mainly all in LzmaLib

**Comment by CoderOffka** [comment]
https://github.com/CoderOffka/ReplayRidor/commit/e8758f7f23ebdcb1d7b9b198ac69fe0d1164b918
