### ISSUE TITLE
Lag on Sliders

### ISSUE THREAD

**Issue by Inappreciation** [CoderOffka/ReplayRidor#9]
I choose a replay and I start to play, it all goes fine and then everytime it goes to a slider it goes to 0fps, the game freezes up and doesnt hit the slider. After a few sliders have passed and its only circles - the lag goes.
I've tried Stable and Beta on osu! and no change. I'm using Windows 10. When it lags it also shows a box that says there was an error calculating the timing because of audio/sound drivers and that the play wont be submitted. I tested to see if this was the replay bot and when its closed, I don't get the error - that is also because of the replay bot.

**Comment by CoderOffka** [comment]
It's not a ReplayRidor's problem. Bcuz the ReplayRidor doesn't read game objects like sliders or smth.
